import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav-comps/Navbar";
import React from "react";
import {AuthProvider} from "@/app/context/AuthProvider";
import {FontProviders} from "@/app/providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "SnapCart",
    description: "Generated by create next app",
    icons: [
        {rel: "icon", url: "/icon.png", type: "image/png"},
    ]
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <FontProviders>
            <AuthProvider>
                <Navbar/>
                {children}
            </AuthProvider>
        </FontProviders>
        </body>
        </html>
    );
}
